title: GraphicsPosting

description: > # this means to ignore newlines until "baseurl:"
  This is a blog for much of the things I learned about shader programming. The purpose is to journal things you and I may need later on.

# social links
github_username: brimson # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
